---
name: cmpsc-302-spring-2019-practical8
break: true
indent: 4
---
# --> check the source code for various characteristics
# note that without an "--exact" the check is an "at least"
src/www/:
    index.html:
        --fragment "TODO" --count 0 --exact
        --fragment "button data-font" --count 4 --exact
        --fragment "div class" --count 1 --exact
        --fragment "wrapper" --count 1 --exact
src/www/css/:
        site.css:
            --fragment "TODO" --count 0 --exact
            --exists
src/www/js/:
        fontchange.js:
            --fragment "TODO" --count 0 --exact
            --exists
# --> check the submission image exists
images/javascript_submission.png:
    --exists
# --> check the number of commits beyond a threshold
--commits 10
# --> check that the linter executes and produces 0 lines of output
--command "htmlhint src/www/index.html" --executes
--command "htmlhint src/www/index.html" --count 1 --exact
--command "htmlhint src/www/index.html" --fragment "no errors found" --count 1 --exact
